name: Auto Fetch RSS

# grant the built-in GITHUB_TOKEN write access so it can push back to the repo
permissions:
  contents: write

# cron schedule + manual trigger
on:
  schedule:
    - cron: '0 3 * * *'       # 毎日 UTC 3:00（日本時間12:00）に実行
  workflow_dispatch:          # Actions タブから手動トリガー可

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # GITHUB_TOKEN を push に使う

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Fetch RSS & generate MD
        run: node fetch_rss.js
        env:
          RSS_URL: ${{ secrets.RSS_URL }}

      - name: Commit & Push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts/
          git diff --quiet || git commit -m "chore: update RSS posts"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
