# 1  ── ワークフローの見出し（Actions タブに表示される名称）
name: Auto Fetch RSS

permissions:
  contents: write

# 4  ── 実行トリガーの定義
on:
  schedule:
    - cron: '0 3 * * *'       # 毎日 UTC 3:00 実行（日本時間 12:00）
  workflow_dispatch:          # 手動実行ボタンも有効化

jobs:
  build:
    # 11 ── 実行環境
    runs-on: ubuntu-latest

    steps:
      # 15 ── リポジトリをチェックアウト（コードを取得）
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # GITHUB_TOKEN を次ステップで使えるように保持

      # 20 ── Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 25 ── 依存パッケージのインストール
      - name: Install dependencies
        run: npm ci

      # 30 ── RSS 取得＆Markdown 生成
      - name: Fetch RSS & generate MD
        run: node fetch_rss.js
        env:
          RSS_URL: ${{ secrets.RSS_URL }}    # リポジトリシークレットに登録済みの RSS フィード URL

      # 36 ── 変更をコミット＆プッシュ
      - name: Commit & Push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _posts/
          git diff --quiet || git commit -m "chore: update RSS posts"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # 自動提供されるトークン
